### ISSUE TITLE
Problems encountered during training

### ISSUE THREAD

**Issue by ZWXCV** [XiaojunTang22/ICCV2023-DDGNet#1]
Hello, author. I had the following problems while training with the code you published:
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    loss = train(itr, dataset, args, model, optimizer, device)
  File "/17106/zwx/ICCV2023-DDGNet-main/train.py", line 40, in train
    wandb.log(loss_dict)
  File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 420, in wrapper
    return func(self, *args, **kwargs)
  File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 371, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
  File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1820, in log
    self._log(data=data, step=step, commit=commit)
  File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1595, in _log
    self._partial_history_callback(data, step, commit)
  File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1467, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 569, in publish_partial_history
    self._publish_partial_history(partial_history)
  File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 89, in _publish_partial_history
    self._publish(rec)
  File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
wandb: While tearing down the service manager. The following error has occurred: [Errno 32] Broken pipe

Is there any way you can solve it? Looking forward to your reply, thank you very much.

**Comment by XiaojunTang22** [comment]
Sorry, I haven't encountered the problem. It seems that wandb goes wrong, and you can add "--without_wandb" to the script for training.

**Comment by XiaojunTang22** [comment]
> Sorry, I haven't encountered the problem. It seems that wandb goes wrong, and you can add "--without_wandb" to the script for training.

**Comment by XiaojunTang22** [comment]
> Hello, author. I had the following problems while training with the code you published: Traceback (most recent call last): File "main.py", line 69, in loss = train(itr, dataset, args, model, optimizer, device) File "/17106/zwx/ICCV2023-DDGNet-main/train.py", line 40, in train wandb.log(loss_dict) File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 420, in wrapper return func(self, *args, **kwargs) File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 371, in wrapper_fn return func(self, *args, **kwargs) File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 361, in wrapper return func(self, *args, **kwargs) File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1820, in log self._log(data=data, step=step, commit=commit) File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1595, in _log self._partial_history_callback(data, step, commit) File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1467, in _partial_history_callback self._backend.interface.publish_partial_history( File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 569, in publish_partial_history self._publish_partial_history(partial_history) File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 89, in _publish_partial_history self._publish(rec) File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish self._sock_client.send_record_publish(record) File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish self.send_server_request(server_req) File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request self._send_message(msg) File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message self._sendall_with_error_handle(header + data) File "/root/anaconda3/envs/ddgnet/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle sent = self._sock.send(data) BrokenPipeError: [Errno 32] Broken pipe wandb: While tearing down the service manager. The following error has occurred: [Errno 32] Broken pipe
> 
> Is there any way you can solve it? Looking forward to your reply, thank you very much.

Sorry, I haven't encountered the problem. It seems that wandb goes wrong, and you can add "--without_wandb" to the script for training.

**Comment by ZWXCV** [comment]
Hello author, how can I obtain visual results of the test?

**Comment by ZWXCV** [comment]
And I want to know how do I get the difference between the location result and the ground truth value。Looking forward to your reply, thank you very much。

**Comment by ZWXCV** [comment]
And I want to know how do I get the difference between the location result and the ground truth value.Looking forward to your reply, thank you very much.

**Comment by XiaojunTang22** [comment]
> And I want to know how do I get the difference between the location result and the ground truth value.Looking forward to your reply, thank you very much.

Localization results depend on attention weights and corresponding thresholds. I suggest you familiarize yourself with the process of generating localization results. I use bar charts to show visual results.

**Comment by ZWXCV** [comment]
Hello author, can I obtain the dataset of your original Thumos14 video? There are many videos in the training set of the Thumos14 dataset that I downloaded that conflict with the t-start in the ground truth. For example, the t-start is 480, but the original video I downloaded only has 450 seconds, which is very confusing for me. I look forward to your reply. Thank you.

**Comment by XiaojunTang22** [comment]
> Hello author, can I obtain the dataset of your original Thumos14 video? There are many videos in the training set of the Thumos14 dataset that I downloaded that conflict with the t-start in the ground truth. For example, the t-start is 480, but the original video I downloaded only has 450 seconds, which is very confusing for me. I look forward to your reply. Thank you.

We use the features provided by MM 2021 paper: Cross-modal Consensus Network for Weakly Supervised Temporal Action Localization. I guess there might have been a mistake in the annotation.

**Comment by ZWXCV** [comment]
Thank you very much for your prompt reply.These are some properties of the ground truth that I output, such as vedio_test_0000007. The corresponding vedio_test_0000007 action in the thumbs14 dataset is correct, but it only takes 482 seconds. I thought it was a problem with the dataset, but downloading and checking it on the official website was not wrong. This is a magical error.
                    video-id        t-start  t-end  label
0     video_test_0000004        0      2      5
1     video_test_0000004       18     19      5
2     video_test_0000004       29     32      5
3     video_test_0000004       44     46      5
4     video_test_0000004        2      2      6
5     video_test_0000004       32     35      6
6     video_test_0000004       47     50      6
7     video_test_0000006       29     90     19
8     video_test_0000007      431    436     12
9     video_test_0000007      440    445     12
10    video_test_0000007      485    489     12
11    video_test_0000007      495    499     12
12    video_test_0000007      543    547     12
13    video_test_0000007      549    554     12
14    video_test_0000007      561    566     12
15    video_test_0000007      610    617     12
16    video_test_0000007      623    628     12
17    video_test_0000007      674    679     12
18    video_test_0000007      682    687     12
19    video_test_0000007      732    738     12

**Comment by XiaojunTang22** [comment]
1 second equals 25(fps)/16(the number of frames contained in each snippet) snippets, so 482 seconds are approximately equal to 753 snippets. I guess t-start (or t-end) denotes the location of the snippet. You can check it.

**Comment by XiaojunTang22** [comment]
> Thank you very much for your prompt reply.These are some properties of the ground truth that I output, such as vedio_test_0000007. The corresponding vedio_test_0000007 action in the thumbs14 dataset is correct, but it only takes 482 seconds. I thought it was a problem with the dataset, but downloading and checking it on the official website was not wrong. This is a magical error. video-id t-start t-end label 0 video_test_0000004 0 2 5 1 video_test_0000004 18 19 5 2 video_test_0000004 29 32 5 3 video_test_0000004 44 46 5 4 video_test_0000004 2 2 6 5 video_test_0000004 32 35 6 6 video_test_0000004 47 50 6 7 video_test_0000006 29 90 19 8 video_test_0000007 431 436 12 9 video_test_0000007 440 445 12 10 video_test_0000007 485 489 12 11 video_test_0000007 495 499 12 12 video_test_0000007 543 547 12 13 video_test_0000007 549 554 12 14 video_test_0000007 561 566 12 15 video_test_0000007 610 617 12 16 video_test_0000007 623 628 12 17 video_test_0000007 674 679 12 18 video_test_0000007 682 687 12 19 video_test_0000007 732 738 12

1 second equals 25(fps)/16(the number of frames contained in each snippet) snippets, so 482 seconds are approximately equal to 753 snippets. I guess t-start (or t-end) denotes the location of the snippet. You can check it.
